name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        sudo apt-get install -y golang
        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install -y dotnet-sdk-6.0
        sudo apt-get install -y python3.9

    - name: Build
      run: |
        chmod +x build-script.sh
        ./build-script.sh

